services:
  level1:
    image: php:8.1-apache
    container_name: level1
    ports:
      - "8081:80"
    volumes:
      - ./level1:/var/www/html
    restart: always
  level2:
    image: php:8.1-apache
    container_name: level2
    ports:
      - "8082:80"
    volumes:
      - ./level2:/var/www/html
    restart: always